Repository townteki/townsquare, pull requests merged in 2022-09, with the labels that each got.

#1478 Fix various bugs
  server/game/CardSelectors/BaseCardSelector.js
  server/game/GameActions/Search.js
  server/game/cards/01-DTR/CharliesPlace.js
  server/game/cards/01-DTR/MorganResearchInstitute.js
  server/game/cards/02.3-EDS/TheMayorsOffice.js
  server/game/cards/03-FF/FasterOnTheDraw.js
  server/game/cards/04.1-FJ/FuntimeFreddy.js
  server/game/cards/07.1-DDeeds/DisgenuineCurrencyPress.js
  server/game/cards/08-GT/SilentSigil.js
  server/game/cards/10-BMR/NickelNightInn.js
  server/game/cards/14-HCWM/FanninTheHammer.js
  server/game/cards/15-W2D/DrJTGoodenough.js
  server/game/cards/15-W2D/HeathsCuriosityShoppe.js
  server/game/cards/16-DT2/BassReeves.js
  server/game/cards/16-DT2/LauraBanks.js
  server/game/cards/16-DT2/ThirstForBlood.js
Labels: bug :bug:

#1468 Card: DTR - Lady Luck
  docs/cardpool-status.md
  server/game/cards/01-DTR/LadyLuck.js
Labels: card-script :black_joker:

#1484 WWE Spirit Trail not providing adjacency
  server/game/cards/05-IOUF/SpiritTrail.js
Labels: bug :bug:

#1483 Update DrawCards action in case not enough in deck
  server/game/GameActions/DrawCards.js
Labels: bug :bug:

#1465 Card: FP - Martyr's Cry
  docs/cardpool-status.md
  server/game/cards/07.2-FP/MartyrsCry.js
Labels: card-script :black_joker:

#1471 Card: FJ - Legal Instruments
  docs/cardpool-status.md
  server/game/cards/04.1-FJ/LegalInstruments.js
Labels: card-script :black_joker:

#1472 Card: FF - Under the Weather
  docs/cardpool-status.md
  server/game/cards/03-FF/UnderTheWeather.js
Labels: card-script :black_joker:

#1475 Card: AGE - Lighting the Fuse
  docs/cardpool-status.md
  server/game/cards/09.2-AGE/LightingTheFuse.js
Labels: card-script :black_joker:

#1481 Do not invent when dropping gadget into play
  server/game/GameActions/PutIntoPlay.js
  server/game/PlayActions/PutIntoPlayCardAction.js
  server/game/ServerCommands/DropCommand.js
  server/game/cards/15-W2D/JohnAcesRadcliffeExp1.js
  server/game/player.js
  test/helpers/playerinteractionwrapper.js
Labels: bug :bug:

#1482 Update job posse forming
  server/game/gamesteps/shootout.js
Labels: bug :bug:

#1486 Solo: Fix selecting scientist when inventing
  server/game/Solo/automaton.js
Labels: bug :bug:, solo

#1487 Fix when not enough cards to make draw hand
  server/game/gamesteps/shootout/drawhandprompt.js
  server/game/handresult.js
  server/game/player.js
Labels: bug :bug:

#1443 Fixed so that player doesn't take casualties.
  server/game/cards/11-TCaR/Disarm.js
Labels: bug :bug:

#1445 Added town square as a legal location
  server/game/gamelocation.js
Labels: bug :bug:

#1493 Fix full blank blanking game actions
  server/game/cardaction.js
Labels: bug :bug:

#1491 Add Discord chat widget
  server/api/account.js
  server/models/User.js
Labels: enhancement :rocket:

#1497 Fix Byron Decker
  server/game/GameActions/AceCard.js
  server/game/cards/13-O4B/ByronDecker.js
Labels: bug :bug:

#1498 Do not invent when reattaching in game
  server/game/player.js
Labels: bug :bug:

#1500 Update dudes leaving posse after job
  server/game/GameActions/MoveDude.js
  server/game/gamesteps/shootout.js
  test/server/integration/jobaction.spec.js
Labels: bug :bug:

#1499 Fixes for minor bugs
  server/game/PlayActions/PutIntoPlayCardAction.js
  server/game/cards/01-DTR/LawrenceBlackwood.js
  server/game/cards/07.1-DDeeds/DisgenuineCurrencyPress.js
  server/game/cards/08-GT/NotaryPublic.js
  server/game/cards/10-BMR/NickelNightInn.js
  server/game/cards/13-O4B/OfficeOfAncestralAffairs.js
  server/game/cards/14-HCWM/Crystal Palace.js
  server/game/cards/16-DT2/DisingenuineCurrencyPress2.js
  server/game/cards/16-DT2/MountMoriahCemetery.js
  server/game/spellcard.js
Labels: bug :bug:

#1501 Publish Discord chat widget
  server/api/account.js
  server/models/User.js
Labels: enhancement :rocket:

#1503 Prevent action to play in any window
  server/game/playTypeAbility.js
Labels: bug :bug:

#1506 Add equals to test player
  server/game/player.js
Labels: bug :bug:

#1504 Add Keep Selected button to draw hand
  server/game/game.js
Labels: enhancement :rocket:, ui

#1507 Add support for filtering buttons in UI
  server/game/basecard.js
Labels: enhancement :rocket:, ui

#1508 Fix FarnumsConsortium.js
  server/game/cards/16-DT2/FarnumsConsortium.js
Labels: bug :bug:

#1509 Remove saving logic
  docs/implementing-cards.md
  server/game/AttachmentValidityCheck.js
  server/game/GameActions/DiscardCard.js
  server/game/GameActions/RemoveFromGame.js
  server/game/GameActions/ReturnCardToHand.js
  server/game/GameActions/index.js
  server/game/GroupedCardEvent.js
  server/game/ServerCommands/DropCommand.js
  server/game/Solo/Archetypes/GunfighterArchetype.js
  server/game/Solo/automaton.js
  server/game/cards/01-DTR/AbramGrothe.js
  server/game/cards/01-DTR/Kidnappin.js
  server/game/cards/01-DTR/RamiroMendoza.js
  server/game/cards/02.1-NTNR/TheRDRanch.js
  server/game/cards/02.3-EDS/TheEvidence.js
  server/game/cards/03-FF/LayOnHands.js
  server/game/cards/03-FF/ThisllHurtInTheMornin.js
  server/game/cards/04.2-NTB/CookinUpTrouble.js
  server/game/cards/04.3-NN/NathanShane.js
  server/game/cards/07.3-BadM/ArnoldStewart.js
  server/game/cards/07.3-BadM/FocusingChi.js
  server/game/cards/07.3-BadM/Mugging.js
  server/game/cards/07.3-BadM/VasilisTheBoar.js
  server/game/cards/08-GT/SightBeyondSight.js
  server/game/cards/09.2-AGE/SunTouchedRaven.js
  server/game/cards/10-BMR/BurnEmOut.js
  server/game/cards/12-2T2D/CurseOfFailure.js
  server/game/cards/13-O4B/TenFootPunch.js
  server/game/cards/14-HCWM/SpeaksWithBuffalo.js
  server/game/cards/15-W2D/ArthurDingler.js
  server/game/cards/16-DT2/Kidnappin2.js
  server/game/costs/AceCost.js
  server/game/costs/DiscardFromHandCost.js
  server/game/costs/DiscardFromPlayCost.js
  server/game/costs/ReturnToHandCost.js
  server/game/drawcard.js
  server/game/event.js
  server/game/game.js
  server/game/gamesteps/nightfall/discardtohandsizeprompt.js
  server/game/gamesteps/shootout/takeyerlumpsprompt.js
  server/game/gamesteps/upkeep/upkeepprompt.js
  server/game/player.js
  test/server/GameActions/ReturnCardToHand.spec.js
  test/server/ServerCommands/DropCommand.spec.js
  test/server/gamesteps/eventwindow.spec.js
Labels: refactor :bomb:

#1514 Update Frontier Feud menu options
  server/game/cards/14-HCWM/FrontierFeud.js
Labels: bug :bug:

#1513 Refactor card hierarchy + TownSquare card
  server/game/basecard.js
  server/game/gamelocation.js
  server/game/nullcard.js
  server/game/townsquarecard.js
Labels: refactor :bomb:
