Repository townteki/townsquare, pull requests merged in 2022-11, with the labels that each got.

#1526 Fix PutIntoPlay action reduction stacking
  server/game/PlayActions/PutIntoPlayCardAction.js
Labels: bug :bug:

#1535 Update publishing workflow
  .github/workflows/bump-version.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish-prod.yml
Labels: workflow

#1536 Bump socket.io to 4.5.3
  package-lock.json
  package.json
  server/gamenode/gameserver.js
  server/lobby.js
  test/server/integration/lobby.spec.js
Labels: dependency

#1538 Add job mark information and highlight
  server/game/drawcard.js
  server/game/dudecard.js
  server/game/gamelocation.js
  server/game/gamesteps/ChooseYesNoPrompt.js
  server/game/gamesteps/shootout.js
  server/log.js
Labels: enhancement :rocket:, ui

#1542 Implement Effects in UI
  server/game/Message.js
  server/game/PlainTextGameChatFormatter.js
  server/game/basecard.js
  server/game/cards/01-DTR/Rumors.js
  server/game/cards/04.3-NN/SwordOfTheSpirit.js
  server/game/cards/07.3-BadM/TheOrphanage.js
  server/game/cards/09.1-TCR/CominUpRoses.js
  server/game/cards/13-O4B/Malison.js
  server/game/cards/13-O4B/Scattergun.js
  server/game/cards/13-O4B/TwilightIsUponUs.js
  server/game/cards/15-W2D/LewisGrizzlyEvans.js
  server/game/cards/16-DT2/FireOfNanahbozho2.js
  server/game/cards/16-DT2/SwordOfTheSpirit2.js
  server/game/drawcard.js
  server/game/effect.js
  server/game/effectengine.js
  server/game/effects.js
  server/game/gamesteps/shootout.js
  server/game/player.js
  test/server/Message.spec.js
  test/server/card/basecard.spec.js
  test/server/card/drawcard.attachments.spec.js
  test/server/card/drawcard.getsummary.spec.js
  test/server/cards/cancreatecards.spec.js
Labels: enhancement :rocket:, ui

#1545 Update dev workflow to prevent version bump
  .github/workflows/publish-dev.yml
Labels: workflow

#1546 Fix Type Errors reported by Sentry
  server/game/cards/12-2T2D/KevinWainwrightExp1.js
  server/game/player.js
Labels: bug :bug:

#1544 Implement Effects in UI
  .github/workflows/publish-dev.yml
  server/game/Message.js
  server/game/PlainTextGameChatFormatter.js
  server/game/basecard.js
  server/game/cards/01-DTR/Rumors.js
  server/game/cards/04.3-NN/SwordOfTheSpirit.js
  server/game/cards/07.3-BadM/TheOrphanage.js
  server/game/cards/09.1-TCR/CominUpRoses.js
  server/game/cards/13-O4B/Malison.js
  server/game/cards/13-O4B/Scattergun.js
  server/game/cards/13-O4B/TwilightIsUponUs.js
  server/game/cards/15-W2D/LewisGrizzlyEvans.js
  server/game/cards/16-DT2/FireOfNanahbozho2.js
  server/game/cards/16-DT2/SwordOfTheSpirit2.js
  server/game/drawcard.js
  server/game/effect.js
  server/game/effectengine.js
  server/game/effects.js
  server/game/gamesteps/shootout.js
  server/game/player.js
  test/server/Message.spec.js
  test/server/card/basecard.spec.js
  test/server/card/drawcard.attachments.spec.js
  test/server/card/drawcard.getsummary.spec.js
  test/server/cards/cancreatecards.spec.js
Labels: enhancement :rocket:

#1502 Fix Jokers used by card abilities
  server/game/player.js
Labels: bug :bug:

#1540 GroutAndSpackle2
  server/game/cards/01-DTR/HidingInTheShadows.js
  server/game/cards/01-DTR/TheSloaneGang.js
  server/game/cards/07.3-BadM/WillaMaeMacGowan.js
  server/game/cards/10-BMR/ChristinePerfect.js
  server/game/cards/13-O4B/BayouVermilionRailroad.js
  server/game/cards/14-HCWM/Crystal Palace.js
Labels: bug :bug:

#1550 Add nulllocation to return if no shootout location
  server/game/cards/01-DTR/BuffaloRifle.js
  server/game/cards/02.2-DD/AngelicaEspinosa.js
  server/game/cards/04.1-FJ/ShaneGravesSecurity.js
  server/game/cards/09.2-AGE/SiegeOfTheOrphanage.js
  server/game/cards/09.3-TSs/GhostlyCommunion.js
  server/game/cards/11-TCaR/AdrianVallejo.js
  server/game/cards/11-TCaR/JasperStone.js
  server/game/cards/11-TCaR/Raven.js
  server/game/game.js
  server/game/gamelocation.js
  server/game/gamesteps/shootout.js
  server/game/nulllocation.js
Labels: bug :bug:

#1551 Fix onTargetsChosen redirect and dynamic effects
  server/game/baseability.js
  server/game/cards/15-W2D/FallenStar.js
  server/game/effects.js
  server/game/gamesteps/TriggeredAbilityWindow.js
  server/game/gamesteps/TriggeredAbilityWindowTitles.js
  test/server/effects/dynamickeywords.spec.js
Labels: bug :bug:

#1552 Add cheatin' info to shootout panel
  server/game/gamesteps/shootout.js
Labels: enhancement :rocket:, ui

#1553 Fix LayOnHands2 and paying costs
  server/game/cards/16-DT2/LayOnHands2.js
  server/game/costs.js
  server/game/costs/MoveTokenFromSelfCost.js
  server/game/costs/ParentCost.js
  server/game/costs/SelfCost.js
  server/game/costs/SpecificCardCost.js
  test/server/cards/01-DTR/BabbleOn.spec.js
Labels: bug :bug:
